### ISSUE TITLE
CUDA Error: __global__ function call is not configured: Permission denied

### ISSUE THREAD

**Issue by imkhairulikhwan** [pjreddie/darknet#1164]
Hi and good day, 

I found similar issue stated here #348 , but I still get the same error even after setting up cuDNN in CMakelists.txt.

I was trying to run darknet_ros in Jetson TX2 connected to DJI M210, as in the attachment. 

![error during launch darknet_ros](https://user-images.githubusercontent.com/4214164/46595950-4fe19f80-cb0d-11e8-888e-c7b5d622f94b.jpg)

As the issue was regarding the permission, perhaps there were steps that I missed?

Thank you in advance!

**Comment by imkhairulikhwan** [comment]
Would there be anyone facing the same issue before?

Thank you!

**Comment by Doylegyf** [comment]
I found the problem is Cudnn permission.
I have solved the problem by using su root.
I also run darknet_ros in Jetson TX2 connected to DJI M210.

**Comment by potBagMeat** [comment]
I also run darknet_ros in Jetson TX2(the manifold 2-G) connected to DJI M210 and faced the same problem...

**Comment by snakehaihai** [comment]
> I also run darknet_ros in Jetson TX2(the manifold 2-G) connected to DJI M210 and faced the same problem...

Iam also running on DJI manifold 2 G.  managed to run it


![image](https://user-images.githubusercontent.com/6070995/86198463-43776300-bb8a-11ea-9bc0-4526ea5c3b21.png)

![image](https://user-images.githubusercontent.com/6070995/86198505-55590600-bb8a-11ea-8441-d928f00153b1.png)
