### ISSUE TITLE
YOLOv3 on GPU: CUDA error: invalid device symbol

### ISSUE THREAD

**Issue by jennigato** [pjreddie/darknet#1478]
I'm trying to train tiny yolov3 on GPU with NViDIA RTX 2080 on Ubantu 18.04. After running
```
./darknet detector train data/football.data cfg/yolov3-tiny-football.cfg yolov3-tiny.conv.15 
```
I get the error message:

```
Loading weights from yolov3-tiny.conv.15...Done!
Learning Rate: 0.001, Momentum: 0.9, Decay: 0.0005
Resizing
416
Loaded: 0.000058 seconds
CUDA Error: invalid device symbol
darknet: ./src/cuda.c:36: check_error: Assertion `0' failed.
Aborted
```
I initially had CUDA 10.0 so I added -gencode=arch=compute_70,code=sm_70 \
 -gencode=arch=compute_75,code=sm_75 to my Makefile but it gave me the error

```
tmpxft_0001d7da_00000000-5_convolutional_kernels.compute_75.cudafe1.cpp:(.text+0x578): undefined reference to `__cudaPopCallConfiguration'
```
so I removed arch 70/75 and changed it to CUDA 9.0, which removed the compilation error but started giving me the invalid device symbol error - my Makefile right now is as below:

```
GPU=1                                                                                                                                                 
CUDNN=0                                                                                                                                               
OPENCV=0                                                                                                                                              
OPENMP=0                                                                                                                                              
DEBUG=0                                                                                                                                               
                                                                                                                                                                                                                             
ARCH= -arch=sm_50   \                                                                                                                                 
 -gencode=arch=compute_50,code=sm_50 \                                                                                                                
 -gencode=arch=compute_52,code=sm_52 \                                                                                                                
 -gencode=arch=compute_60,code=sm_60 \                                                                                                                
 -gencode=arch=compute_61,code=sm_61 \ 
```

Running nvidia-smi gives me:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 415.18       Driver Version: 415.18       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  On   | 00000000:09:00.0 Off |                  N/A |
| 63%   68C    P2   176W / 180W |   5876MiB / 10989MiB |     99%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 208...  On   | 00000000:42:00.0  On |                  N/A |
| 71%   72C    P2   172W / 180W |   5956MiB / 10989MiB |     99%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     80518      C   ./bminer                                    5865MiB |
|    1      5669      G   /usr/lib/xorg/Xorg                            79MiB |
|    1     80518      C   ./bminer                                    5865MiB |
+-----------------------------------------------------------------------------+
```

I get the idea it's some sort of version mismatch- any help is appreciated!

**Comment by clementyau** [comment]
Since you have 2080 Ti, can you try using just the line below with CUDA 10.0? It worked for me with RTX 2070.

ARCH= -gencode arch=compute_75,code=[sm_75,compute_75]

**Comment by clemente620** [comment]
sudo ./darknet detector train data/football.data cfg/yolov3-tiny-football.cfg yolov3-tiny.conv.15

**Comment by bertalanimre** [comment]
Any update on this? I'm facing similar issue with RTX 2060

```
GPU=1
CUDNN=0
OPENCV=1
OPENMP=0
DEBUG=0

ARCH= -gencode arch=compute_30,code=sm_30 \
      -gencode arch=compute_35,code=sm_35 \
      -gencode arch=compute_50,code=[sm_50,compute_50] \
      -gencode arch=compute_52,code=[sm_52,compute_52] \
      -gencode arch=compute_75,code=[sm_75,compute_75]
```

```
0 ✓ bi@Nvidia-Learning ~/darknet $ ./darknet -i 1 imagenet test cfg/alexnet.cfg alexnet.weights
CUDA Error: invalid device ordinal
darknet: ./src/cuda.c:36: check_error: Assertion `0' failed.
Aborted
```

```
0 ✓ bi@Nvidia-Learning ~/darknet $ nvidia-smi
Mon May 27 13:18:55 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.67       Driver Version: 418.74       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 2060    Off  | 00000000:06:00.0 Off |                  N/A |
| 19%   50C    P0     1W / 160W |      0MiB /  5904MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by Samuel-Nathanson** [comment]
Hi, I am running into the same issue - 

After changing the ARCH parameter to this, darknet no longer compiles. 
ARCH= -gencode arch=compute_75,code=[sm_75,compute_75]
...
...
nvcc fatal   : Unsupported gpu architecture 'compute_75'

The output of nvidia-smi is as follows:
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.87.00    Driver Version: 418.87.00    CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  On   | 00000000:01:00.0  On |                  N/A |
| N/A   46C    P8    12W /  N/A |    735MiB /  7952MiB |      7%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1288      G   /usr/lib/xorg/Xorg                            34MiB |
|    0      1393      G   /usr/bin/gnome-shell                          57MiB |
|    0      1732      G   /usr/lib/xorg/Xorg                           291MiB |
|    0      1874      G   /usr/bin/gnome-shell                         148MiB |
|    0      2459      G   ...equest-channel-token=393258947124571722   129MiB |
|    0     19473      G   ...uest-channel-token=16372698014484088888    33MiB |
|    0     29605      G   ...p/pycharm-professional/151/jbr/bin/java    26MiB |
+-----------------------------------------------------------------------------+

**Comment by josefernandez91** [comment]
Architecture 75 is only supporting as of CUDA 10.0

**Comment by DCMMC** [comment]
Same error there when I used CUDA 10.1 and 2080 Ti.
Downgrade CUDA 10.1 to CUDA 10.0 fixed this error.

**Comment by lpmrz** [comment]
I am having the same issue with RTX 3070. If I add -gencode=arch=compute_86,code=compute_86 to the cmake list. Compilation gives error. If a remove it, I get the error below;

Waiting for image.
CUDA Error: invalid device symbol
CUDA Error: invalid device symbol: Success
[darknet_ros-1] process has died [pid 6202, exit code 255, cmd /home/dronelab/catkin_ws/devel/lib/darknet_ros/darknet_ros camera/rgb/image_raw:=/camera/rgb/image_raw __name:=darknet_ros __log:=/home/dronelab/.ros/log/c257fef2-517e-11eb-9938-18c04d79b5a9/darknet_ros-1.log].
log file: /home/dronelab/.ros/log/c257fef2-517e-11eb-9938-18c04d79b5a9/darknet_ros-1*.log

nvidia-smi gives the output below;

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.45.01    Driver Version: 455.45.01    CUDA Version: 11.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 3070    Off  | 00000000:01:00.0  On |                  N/A |
|  0%   48C    P8    19W / 240W |    301MiB /  7979MiB |      1%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1137      G   /usr/lib/xorg/Xorg                 26MiB |
|    0   N/A  N/A      1210      G   /usr/bin/gnome-shell               53MiB |
|    0   N/A  N/A      2174      G   /usr/lib/xorg/Xorg                162MiB |
|    0   N/A  N/A      2320      G   /usr/bin/gnome-shell               50MiB |
|    0   N/A  N/A      2938      G   /usr/lib/firefox/firefox            3MiB |
+-----------------------------------------------------------------------------+

Does anyone solved the problem. Any suggestions?

**Comment by lpmrz** [comment]
Hello everyone, I followed this guys steps and it worked like a charm. Hope this helps;
https://e21342892.medium.com/cuda-cudnn-opencv-yolo%E5%AE%89%E8%A3%9Don-rtx3080-26e9f5da0e8f

**Comment by HHendy69** [comment]
@ipmrz any update on your error? I am stucking there
