### ISSUE TITLE
CUDA status Error: file: ./src/dark_cuda.c : () : line: 239 : build time: Apr 16 2020 - 16:43:48 

### ISSUE THREAD

**Issue by SK124** [pjreddie/darknet#2117]
Allocate additional workspace_size = 49.84 MB 
Loading weights from darknet53.conv.74...
 seen 64, trained: 0 K-images (0 Kilo-batches_64) 
Done! Loaded 75 layers from weights-file 

 Error: You set incorrect value batch=1 for Training! You should set batch=64 subdivision=64 
batch=64 subdivision=64
Learning Rate: 0.001, Momentum: 0.9, Decay: 0.0005
Resizing, random_coef = 1.40 

 608 x 608 
 try to allocate additional workspace_size = 106.46 MB 
 CUDA allocate done! 
Loaded: 0.000055 seconds
CUDA status Error: file: ./src/dark_cuda.c : () : line: 239 : build time: Apr 16 2020 - 16:43:48 

 CUDA Error: invalid argument
CUDA Error: invalid argument: File exists
darknet: ./src/utils.c:325: error: Assertion `0' failed.

**Comment by kir486680** [comment]
i have the same issue on colab

**Comment by kir486680** [comment]
@SK124 I solved that issue by downloading darknet like that 
```
!ls
!cd /content
!rm -fr darknet
!git clone https://github.com/AlexeyAB/darknet/
% cd darknet
!sed -i 's/OPENCV=0/OPENCV=1/g' Makefile
!sed -i 's/GPU=0/GPU=1/g' Makefile
!sed -i 's/CUDNN=0/CUDNN=1/g' Makefile
!apt update
!apt-get install libopencv-dev
```

**Comment by Partha-Sarker** [comment]
> @SK124 I solved that issue by downloading darknet like that
> 
> ```
> !ls
> !cd /content
> !rm -fr darknet
> !git clone https://github.com/AlexeyAB/darknet/
> % cd darknet
> !sed -i 's/OPENCV=0/OPENCV=1/g' Makefile
> !sed -i 's/GPU=0/GPU=1/g' Makefile
> !sed -i 's/CUDNN=0/CUDNN=1/g' Makefile
> !apt update
> !apt-get install libopencv-dev
> ```

that worked for me

**Comment by sba17** [comment]
updated subdivision as 64 and resolved the issue.

**Comment by Janani130399** [comment]
If you are using Google colab. Then check your GPU settings in colab.

**Comment by ashishaassi21** [comment]
I did this but then I started getting this error
/bin/bash: .cd/content/darknet: No such file or directory
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)

**Comment by kaushik-bhatt** [comment]
I tried so many things. Also, tried dos2unix(), turned to ubuntu, but getting same error. After that I tried this, which really solved my problem.

!git clone https://github.com/AlexeyAB/darknet/
% cd darknet
!sed -i 's/OPENCV=0/OPENCV=1/g' Makefile
!sed -i 's/GPU=0/GPU=1/g' Makefile
!sed -i 's/CUDNN=0/CUDNN=1/g' Makefile
!apt update
!apt-get install libopencv-dev


There is nothing wrong with files copied from windows or linux, problem exist for the the darknet version cloned from:

!git clone 'https://github.com/pjreddie/darknet'

changed it.

**Comment by liu1000** [comment]
I had the same error except it didn't have the last line (`darknet: ./src/utils.c:325: error: Assertion `0' failed.`)

My fix was to remove `max=100` under [yolo] in the config file, [doc](https://github.com/AlexeyAB/darknet/wiki/CFG-Parameters-in-the-different-layers)
