### ISSUE TITLE
darkent CUDA Error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by nyierr** [pjreddie/darknet#2179]
I have built darknet with openCV and CUDA but when you run the following I am ending up with an error:
```
$ ./darknet detector demo cfg/coco.data cfg/yolov3.cfg yolov3.weights
Demo
layer     filters    size              input                output
    0 conv     32  3 x 3 / 1   416 x 416 x   3   ->   416 x 416 x  32  0.299 BFLOPs
    1 conv     64  3 x 3 / 2   416 x 416 x  32   ->   208 x 208 x  64  1.595 BFLOPs
...
  104 conv    256  3 x 3 / 1    52 x  52 x 128   ->    52 x  52 x 256  1.595 BFLOPs
  105 conv    255  1 x 1 / 1    52 x  52 x 256   ->    52 x  52 x 255  0.353 BFLOPs
  106 yolo
CUDA Error: no kernel image is available for execution on the device
darknet: ./src/cuda.c:36: check_error: Assertion `0' failed.
Aborted (core dumped)
```
Any idea how to fix it? My nvidia-smi:
$ nvidia-smi
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.132                Driver Version: 390.132                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GT 630M     Off  | 00000000:01:00.0 N/A |                  N/A |
| N/A   53C    P0    N/A /  N/A |    196MiB /  1985MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0                    Not Supported                                       |
+-----------------------------------------------------------------------------+
```

**Comment by nyierr** [comment]
Found [a solution](https://devporium.wordpress.com/2020/06/08/cuda-error-no-kernel-image-is-available-for-execution-on-the-device/)

**Comment by swapniel99** [comment]
@nyierr What was the solution? the link you provided doesnt exist.

**Comment by MichielJ1998** [comment]
@nyierr I also have the same issue, what was your solution? The link is broken.

**Comment by nyierr** [comment]
@swapniel99 and @MichielJ1998 , please check [https://youcangeek.wordpress.com/2020/06/08/cuda-error-no-kernel-image-is-available-for-execution-on-the-device/](url)

**Comment by MichielJ1998** [comment]
Thanks for answering. I fixed the problem yesterday by installing darknet yolov4, now everything runs fine with CUDA.

**Comment by Chirag-Jariwala** [comment]
> Thanks for answering. I fixed the problem yesterday by installing darknet yolov4, now everything runs fine with CUDA.

How? please explain
