### ISSUE TITLE
Yolov4 from src - Docker and Nvidia-V100 raise cuDNN status Error in: file dark_cuda.c : () : line: 171 

### ISSUE THREAD

**Issue by MI-LA01** [pjreddie/darknet#2213]
Hello, 

While creating a docker container to work on yolov4 I ran into this error to train a custom (but simple) detector. 

```
./darknet detector train data/hails.data cfg/yolov4-hailsnet.cfg yolov4.conv.137 ```
CUDA-version: 10000 (10010), cuDNN: 7.6.5, CUDNN_HALF=1, GPU count: 1  
CUDNN_HALF=1 
OpenCV isn't used - data augmentation will be slow 
Prepare additional network for mAP calculation...
0 : compute_capability = 700, cudnn_half = 1, GPU: Tesla V100-PCIE-16GB 
net.optimized_memory = 0 
mini_batch = 1, batch = 16, time_steps = 1, train = 0 
   layer   filters  size/strd(dil)      input                output
   0 
cuDNN status Error in: file: /usr/src/app/darknet/src/dark_cuda.c : () : line: 171 : build time: Jul  4 2020 - 12:26:50 

cuDNN Error: CUDNN_STATUS_BAD_PARAM
cuDNN Error: CUDNN_STATUS_BAD_PARAM: File exists
```

If we look at the first line 127 of the dark_cuda.c this is just a matter to initialize cuda, so nothing crazy and i suppose then,  the device was not created properly after the cuda_get_device()
```
#ifdef CUDNN
cudnnHandle_t cudnn_handle()
{
    static int init[16] = {0};
    static cudnnHandle_t handle[16];
    int i = cuda_get_device();
    if(!init[i]) {
        cudnnCreate(&handle[i]);
        init[i] = 1;
        cudnnStatus_t status = cudnnSetStream(handle[i], get_cuda_stream());
        CHECK_CUDNN(status); <-- Line 171
    }
    return handle[i];
}

```
My packages are fairly standard ; I've just had to install with apt, 2 missing packages to compile the repository : 
* cublas (+ -dev for headers)
* cudnn (+ -dev for headers)
Otherwise it was not possible to compile (curand.h missing etc.) 
```

ii  cuda-command-line-tools-10-0  10.0.130-1                        amd64        CUDA command-line tools
ii  cuda-compat-10-0              410.104-1                         amd64        CUDA Compatibility Platform
ii  cuda-cublas-10-0              10.0.130-1                        amd64        CUBLAS native runtime libraries
ii  cuda-cublas-dev-10-0          10.0.130-1                        amd64        CUBLAS native dev links, headers
ii  cuda-cudart-10-0              10.0.130-1                        amd64        CUDA Runtime native Libraries
ii  cuda-cudart-dev-10-0          10.0.130-1                        amd64        CUDA Runtime native dev links, headers
ii  cuda-cufft-10-0               10.0.130-1                        amd64        CUFFT native runtime libraries
ii  cuda-cuobjdump-10-0           10.0.130-1                        amd64        CUDA cuobjdump
ii  cuda-cupti-10-0               10.0.130-1                        amd64        CUDA profiling tools interface.
ii  cuda-curand-10-0              10.0.130-1                        amd64        CURAND native runtime libraries
ii  cuda-curand-dev-10-0          10.0.130-1                        amd64        CURAND native dev links, headers
ii  cuda-cusolver-10-0            10.0.130-1                        amd64        CUDA solver native runtime libraries
ii  cuda-cusparse-10-0            10.0.130-1                        amd64        CUSPARSE native runtime libraries
ii  cuda-driver-dev-10-0          10.0.130-1                        amd64        CUDA Driver native dev stub library
ii  cuda-gdb-10-0                 10.0.130-1                        amd64        CUDA-GDB
ii  cuda-gpu-library-advisor-10-0 10.0.130-1                        amd64        CUDA GPU Library Advisor.
ii  cuda-license-10-0             10.0.130-1                        amd64        CUDA licenses
ii  cuda-memcheck-10-0            10.0.130-1                        amd64        CUDA-MEMCHECK
ii  cuda-misc-headers-10-0        10.0.130-1                        amd64        CUDA miscellaneous headers
ii  cuda-nvcc-10-0                10.0.130-1                        amd64        CUDA nvcc
ii  cuda-nvdisasm-10-0            10.0.130-1                        amd64        CUDA disassembler
ii  cuda-nvprof-10-0              10.0.130-1                        amd64        CUDA Profiler tools
ii  cuda-nvtx-10-0                10.0.130-1                        amd64        NVIDIA Tools Extension
ii  libcudnn7                     7.6.5.32-1+cuda10.2               amd64        cuDNN runtime libraries
ii  libcudnn7-dev                 7.6.5.32-1+cuda10.2               amd64        cuDNN development libraries and headers
ii  libnvinfer5                   5.1.5-1+cuda10.0                  amd64        TensorRT runtime libraries
```

For the sake of completeness : 
* My docker image is actually the one from google having tensorflow + python3 and jupyter (tensorflow/tensorflow  2.1.0-gpu-py3-jupyter), I've started from here and then checkout the yolov4 source code and followed the build process through cmake 
* During the CMake build (cmake ../) This Warning was raised : 
```
-- Found CUDNN: //usr/include (found version "7.6.5") 
-- CMAKE_CUDA_FLAGS: -gencode arch=compute_70,code=sm_70 --compiler-options " -Wall -Wno-unused-result -Wno-unknown-pragmas -Wfatal-errors -Wno-deprecated-declarations -Wno-write-strings -DGPU -DCUDNN -fPIC -fopenmp -Ofast " 
-- ZED SDK not found
-- Configuring done
CMake Warning (dev) in CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  CUDA_ARCHITECTURES is empty for target "darknet".
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  CUDA_ARCHITECTURES is empty for target "dark".
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  CUDA_ARCHITECTURES is empty for target "dark".
This warning is for project developers.  Use -Wno-dev to suppress it.
```

* My GPU is working as darknet executable is able to find it and nvidia-smi inside the container gives : 
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.126.02   Driver Version: 418.126.02   CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-PCIE...  Off  | 00000000:B3:00.0 Off |                    0 |
| N/A   61C    P0    47W / 250W |      0MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

Any advices are welcome

**Comment by AlexeyAB** [comment]
It seems something wrong with CUDNN.
Try to download `Makefile` again, set `GPU=1 CUDNN=1 CUDNN_HALF=1` and prefreably `OPENCV=1` in the  Makefile, and build by using command
`make`

will it work successfully?

**Comment by MI-LA01** [comment]
The issue gone by having : 
* git clone from scratch 
* ```apt-get install libopencv-dev```
*  build using make and not cmake (note the arch=compute_50,code=[sm_50,compute_50] is not the same) 
* replacing my cfg file and data

**However a segfault occurred** after running the same cmd :  

```./darknet detector train data/hails.data cfg/yolov4-hailsnet.cfg yolov4.conv.137 ```

-- 

```
yolov4-hailsnet
layer     filters    size              input                output
    0 Couldn't find activation function mish, going with ReLU
conv     32  3 x 3 / 1   320 x 320 x   3   ->   320 x 320 x  32  0.177 BFLOPs
    1 Couldn't find activation function mish, going with ReLU
conv     64  3 x 3 / 2   320 x 320 x  32   ->   160 x 160 x  64  0.944 BFLOPs
    2 Couldn't find activation function mish, going with ReLU
conv     64  1 x 1 / 1   160 x 160 x  64   ->   160 x 160 x  64  0.210 BFLOPs
    3 route  1
    4 Couldn't find activation function mish, going with ReLU
conv     64  1 x 1 / 1   160 x 160 x  64   ->   160 x 160 x  64  0.210 BFLOPs
    5 Couldn't find activation function mish, going with ReLU
conv     32  1 x 1 / 1   160 x 160 x  64   ->   160 x 160 x  32  0.105 BFLOPs
    6 Couldn't find activation function mish, going with ReLU
conv     64  3 x 3 / 1   160 x 160 x  32   ->   160 x 160 x  64  0.944 BFLOPs
    7 res    4                 160 x 160 x  64   ->   160 x 160 x  64
    8 Couldn't find activation function mish, going with ReLU
conv     64  1 x 1 / 1   160 x 160 x  64   ->   160 x 160 x  64  0.210 BFLOPs
    9 route  8 2
   10 Couldn't find activation function mish, going with ReLU
conv     64  1 x 1 / 1   160 x 160 x 128   ->   160 x 160 x  64  0.419 BFLOPs
   11 Couldn't find activation function mish, going with ReLU
conv    128  3 x 3 / 2   160 x 160 x  64   ->    80 x  80 x 128  0.944 BFLOPs
   12 Couldn't find activation function mish, going with ReLU
conv     64  1 x 1 / 1    80 x  80 x 128   ->    80 x  80 x  64  0.105 BFLOPs
   13 route  11
   14 Couldn't find activation function mish, going with ReLU
conv     64  1 x 1 / 1    80 x  80 x 128   ->    80 x  80 x  64  0.105 BFLOPs
   15 Couldn't find activation function mish, going with ReLU
conv     64  1 x 1 / 1    80 x  80 x  64   ->    80 x  80 x  64  0.052 BFLOPs
   16 Couldn't find activation function mish, going with ReLU
conv     64  3 x 3 / 1    80 x  80 x  64   ->    80 x  80 x  64  0.472 BFLOPs
   17 res   14                  80 x  80 x  64   ->    80 x  80 x  64
   18 Couldn't find activation function mish, going with ReLU
conv     64  1 x 1 / 1    80 x  80 x  64   ->    80 x  80 x  64  0.052 BFLOPs
   19 Couldn't find activation function mish, going with ReLU
conv     64  3 x 3 / 1    80 x  80 x  64   ->    80 x  80 x  64  0.472 BFLOPs
   20 res   17                  80 x  80 x  64   ->    80 x  80 x  64
   21 Couldn't find activation function mish, going with ReLU
conv     64  1 x 1 / 1    80 x  80 x  64   ->    80 x  80 x  64  0.052 BFLOPs
   22 route  21 12
   23 Couldn't find activation function mish, going with ReLU
conv    128  1 x 1 / 1    80 x  80 x 128   ->    80 x  80 x 128  0.210 BFLOPs
   24 Couldn't find activation function mish, going with ReLU
conv    256  3 x 3 / 2    80 x  80 x 128   ->    40 x  40 x 256  0.944 BFLOPs
   25 Couldn't find activation function mish, going with ReLU
conv    128  1 x 1 / 1    40 x  40 x 256   ->    40 x  40 x 128  0.105 BFLOPs
   26 route  24
   27 Couldn't find activation function mish, going with ReLU
conv    128  1 x 1 / 1    40 x  40 x 256   ->    40 x  40 x 128  0.105 BFLOPs
   28 Couldn't find activation function mish, going with ReLU
conv    128  1 x 1 / 1    40 x  40 x 128   ->    40 x  40 x 128  0.052 BFLOPs
   29 Couldn't find activation function mish, going with ReLU
conv    128  3 x 3 / 1    40 x  40 x 128   ->    40 x  40 x 128  0.472 BFLOPs
   30 res   27                  40 x  40 x 128   ->    40 x  40 x 128
   31 Couldn't find activation function mish, going with ReLU
conv    128  1 x 1 / 1    40 x  40 x 128   ->    40 x  40 x 128  0.052 BFLOPs
   32 Couldn't find activation function mish, going with ReLU
conv    128  3 x 3 / 1    40 x  40 x 128   ->    40 x  40 x 128  0.472 BFLOPs
   33 res   30                  40 x  40 x 128   ->    40 x  40 x 128
   34 Couldn't find activation function mish, going with ReLU
conv    128  1 x 1 / 1    40 x  40 x 128   ->    40 x  40 x 128  0.052 BFLOPs
   35 Couldn't find activation function mish, going with ReLU
conv    128  3 x 3 / 1    40 x  40 x 128   ->    40 x  40 x 128  0.472 BFLOPs
   36 res   33                  40 x  40 x 128   ->    40 x  40 x 128
   37 Couldn't find activation function mish, going with ReLU
conv    128  1 x 1 / 1    40 x  40 x 128   ->    40 x  40 x 128  0.052 BFLOPs
   38 Couldn't find activation function mish, going with ReLU
conv    128  3 x 3 / 1    40 x  40 x 128   ->    40 x  40 x 128  0.472 BFLOPs
   39 res   36                  40 x  40 x 128   ->    40 x  40 x 128
   40 Couldn't find activation function mish, going with ReLU
conv    128  1 x 1 / 1    40 x  40 x 128   ->    40 x  40 x 128  0.052 BFLOPs
   41 Couldn't find activation function mish, going with ReLU
conv    128  3 x 3 / 1    40 x  40 x 128   ->    40 x  40 x 128  0.472 BFLOPs
   42 res   39                  40 x  40 x 128   ->    40 x  40 x 128
   43 Couldn't find activation function mish, going with ReLU
conv    128  1 x 1 / 1    40 x  40 x 128   ->    40 x  40 x 128  0.052 BFLOPs
   44 Couldn't find activation function mish, going with ReLU
conv    128  3 x 3 / 1    40 x  40 x 128   ->    40 x  40 x 128  0.472 BFLOPs
   45 res   42                  40 x  40 x 128   ->    40 x  40 x 128
   46 Couldn't find activation function mish, going with ReLU
conv    128  1 x 1 / 1    40 x  40 x 128   ->    40 x  40 x 128  0.052 BFLOPs
   47 Couldn't find activation function mish, going with ReLU
conv    128  3 x 3 / 1    40 x  40 x 128   ->    40 x  40 x 128  0.472 BFLOPs
   48 res   45                  40 x  40 x 128   ->    40 x  40 x 128
   49 Couldn't find activation function mish, going with ReLU
conv    128  1 x 1 / 1    40 x  40 x 128   ->    40 x  40 x 128  0.052 BFLOPs
   50 Couldn't find activation function mish, going with ReLU
conv    128  3 x 3 / 1    40 x  40 x 128   ->    40 x  40 x 128  0.472 BFLOPs
   51 res   48                  40 x  40 x 128   ->    40 x  40 x 128
   52 Couldn't find activation function mish, going with ReLU
conv    128  1 x 1 / 1    40 x  40 x 128   ->    40 x  40 x 128  0.052 BFLOPs
   53 route  52 25
   54 Couldn't find activation function mish, going with ReLU
conv    256  1 x 1 / 1    40 x  40 x 256   ->    40 x  40 x 256  0.210 BFLOPs
   55 Couldn't find activation function mish, going with ReLU
conv    512  3 x 3 / 2    40 x  40 x 256   ->    20 x  20 x 512  0.944 BFLOPs
   56 Couldn't find activation function mish, going with ReLU
conv    256  1 x 1 / 1    20 x  20 x 512   ->    20 x  20 x 256  0.105 BFLOPs
   57 route  55
   58 Couldn't find activation function mish, going with ReLU
conv    256  1 x 1 / 1    20 x  20 x 512   ->    20 x  20 x 256  0.105 BFLOPs
   59 Couldn't find activation function mish, going with ReLU
conv    256  1 x 1 / 1    20 x  20 x 256   ->    20 x  20 x 256  0.052 BFLOPs
   60 Couldn't find activation function mish, going with ReLU
conv    256  3 x 3 / 1    20 x  20 x 256   ->    20 x  20 x 256  0.472 BFLOPs
   61 res   58                  20 x  20 x 256   ->    20 x  20 x 256
   62 Couldn't find activation function mish, going with ReLU
conv    256  1 x 1 / 1    20 x  20 x 256   ->    20 x  20 x 256  0.052 BFLOPs
   63 Couldn't find activation function mish, going with ReLU
conv    256  3 x 3 / 1    20 x  20 x 256   ->    20 x  20 x 256  0.472 BFLOPs
   64 res   61                  20 x  20 x 256   ->    20 x  20 x 256
   65 Couldn't find activation function mish, going with ReLU
conv    256  1 x 1 / 1    20 x  20 x 256   ->    20 x  20 x 256  0.052 BFLOPs
   66 Couldn't find activation function mish, going with ReLU
conv    256  3 x 3 / 1    20 x  20 x 256   ->    20 x  20 x 256  0.472 BFLOPs
   67 res   64                  20 x  20 x 256   ->    20 x  20 x 256
   68 Couldn't find activation function mish, going with ReLU
conv    256  1 x 1 / 1    20 x  20 x 256   ->    20 x  20 x 256  0.052 BFLOPs
   69 Couldn't find activation function mish, going with ReLU
conv    256  3 x 3 / 1    20 x  20 x 256   ->    20 x  20 x 256  0.472 BFLOPs
   70 res   67                  20 x  20 x 256   ->    20 x  20 x 256
   71 Couldn't find activation function mish, going with ReLU
conv    256  1 x 1 / 1    20 x  20 x 256   ->    20 x  20 x 256  0.052 BFLOPs
   72 Couldn't find activation function mish, going with ReLU
conv    256  3 x 3 / 1    20 x  20 x 256   ->    20 x  20 x 256  0.472 BFLOPs
   73 res   70                  20 x  20 x 256   ->    20 x  20 x 256
   74 Couldn't find activation function mish, going with ReLU
conv    256  1 x 1 / 1    20 x  20 x 256   ->    20 x  20 x 256  0.052 BFLOPs
   75 Couldn't find activation function mish, going with ReLU
conv    256  3 x 3 / 1    20 x  20 x 256   ->    20 x  20 x 256  0.472 BFLOPs
   76 res   73                  20 x  20 x 256   ->    20 x  20 x 256
   77 Couldn't find activation function mish, going with ReLU
conv    256  1 x 1 / 1    20 x  20 x 256   ->    20 x  20 x 256  0.052 BFLOPs
   78 Couldn't find activation function mish, going with ReLU
conv    256  3 x 3 / 1    20 x  20 x 256   ->    20 x  20 x 256  0.472 BFLOPs
   79 res   76                  20 x  20 x 256   ->    20 x  20 x 256
   80 Couldn't find activation function mish, going with ReLU
conv    256  1 x 1 / 1    20 x  20 x 256   ->    20 x  20 x 256  0.052 BFLOPs
   81 Couldn't find activation function mish, going with ReLU
conv    256  3 x 3 / 1    20 x  20 x 256   ->    20 x  20 x 256  0.472 BFLOPs
   82 res   79                  20 x  20 x 256   ->    20 x  20 x 256
   83 Couldn't find activation function mish, going with ReLU
conv    256  1 x 1 / 1    20 x  20 x 256   ->    20 x  20 x 256  0.052 BFLOPs
   84 route  83 56
   85 Couldn't find activation function mish, going with ReLU
conv    512  1 x 1 / 1    20 x  20 x 512   ->    20 x  20 x 512  0.210 BFLOPs
   86 Couldn't find activation function mish, going with ReLU
conv   1024  3 x 3 / 2    20 x  20 x 512   ->    10 x  10 x1024  0.944 BFLOPs
   87 Couldn't find activation function mish, going with ReLU
conv    512  1 x 1 / 1    10 x  10 x1024   ->    10 x  10 x 512  0.105 BFLOPs
   88 route  86
   89 Couldn't find activation function mish, going with ReLU
conv    512  1 x 1 / 1    10 x  10 x1024   ->    10 x  10 x 512  0.105 BFLOPs
   90 Couldn't find activation function mish, going with ReLU
conv    512  1 x 1 / 1    10 x  10 x 512   ->    10 x  10 x 512  0.052 BFLOPs
   91 Couldn't find activation function mish, going with ReLU
conv    512  3 x 3 / 1    10 x  10 x 512   ->    10 x  10 x 512  0.472 BFLOPs
   92 res   89                  10 x  10 x 512   ->    10 x  10 x 512
   93 Couldn't find activation function mish, going with ReLU
conv    512  1 x 1 / 1    10 x  10 x 512   ->    10 x  10 x 512  0.052 BFLOPs
   94 Couldn't find activation function mish, going with ReLU
conv    512  3 x 3 / 1    10 x  10 x 512   ->    10 x  10 x 512  0.472 BFLOPs
   95 res   92                  10 x  10 x 512   ->    10 x  10 x 512
   96 Couldn't find activation function mish, going with ReLU
conv    512  1 x 1 / 1    10 x  10 x 512   ->    10 x  10 x 512  0.052 BFLOPs
   97 Couldn't find activation function mish, going with ReLU
conv    512  3 x 3 / 1    10 x  10 x 512   ->    10 x  10 x 512  0.472 BFLOPs
   98 res   95                  10 x  10 x 512   ->    10 x  10 x 512
   99 Couldn't find activation function mish, going with ReLU
conv    512  1 x 1 / 1    10 x  10 x 512   ->    10 x  10 x 512  0.052 BFLOPs
  100 Couldn't find activation function mish, going with ReLU
conv    512  3 x 3 / 1    10 x  10 x 512   ->    10 x  10 x 512  0.472 BFLOPs
  101 res   98                  10 x  10 x 512   ->    10 x  10 x 512
  102 Couldn't find activation function mish, going with ReLU
conv    512  1 x 1 / 1    10 x  10 x 512   ->    10 x  10 x 512  0.052 BFLOPs
  103 route  102 87
  104 Couldn't find activation function mish, going with ReLU
conv   1024  1 x 1 / 1    10 x  10 x1024   ->    10 x  10 x1024  0.210 BFLOPs
  105 conv    512  1 x 1 / 1    10 x  10 x1024   ->    10 x  10 x 512  0.105 BFLOPs
  106 conv   1024  3 x 3 / 1    10 x  10 x 512   ->    10 x  10 x1024  0.944 BFLOPs
  107 conv    512  1 x 1 / 1    10 x  10 x1024   ->    10 x  10 x 512  0.105 BFLOPs
  108 max          5 x 5 / 1    10 x  10 x 512   ->    10 x  10 x 512
  109 route  107
  110 max          9 x 9 / 1    10 x  10 x 512   ->    10 x  10 x 512
  111 route  107
  112 max          13 x 13 / 1    10 x  10 x 512   ->    10 x  10 x 512
  113 route  112 110 108 107
  114 conv    512  1 x 1 / 1    10 x  10 x2048   ->    10 x  10 x 512  0.210 BFLOPs
  115 conv   1024  3 x 3 / 1    10 x  10 x 512   ->    10 x  10 x1024  0.944 BFLOPs
  116 conv    512  1 x 1 / 1    10 x  10 x1024   ->    10 x  10 x 512  0.105 BFLOPs
  117 conv    256  1 x 1 / 1    10 x  10 x 512   ->    10 x  10 x 256  0.026 BFLOPs
  118 upsample            2x    10 x  10 x 256   ->    20 x  20 x 256
  119 route  85
  120 conv    256  1 x 1 / 1    20 x  20 x 512   ->    20 x  20 x 256  0.105 BFLOPs
  121 route  120 118
  122 conv    256  1 x 1 / 1    20 x  20 x 512   ->    20 x  20 x 256  0.105 BFLOPs
  123 conv    512  3 x 3 / 1    20 x  20 x 256   ->    20 x  20 x 512  0.944 BFLOPs
  124 conv    256  1 x 1 / 1    20 x  20 x 512   ->    20 x  20 x 256  0.105 BFLOPs
  125 conv    512  3 x 3 / 1    20 x  20 x 256   ->    20 x  20 x 512  0.944 BFLOPs
  126 conv    256  1 x 1 / 1    20 x  20 x 512   ->    20 x  20 x 256  0.105 BFLOPs
  127 conv    128  1 x 1 / 1    20 x  20 x 256   ->    20 x  20 x 128  0.026 BFLOPs
  128 upsample            2x    20 x  20 x 128   ->    40 x  40 x 128
  129 route  54
  130 conv    128  1 x 1 / 1    40 x  40 x 256   ->    40 x  40 x 128  0.105 BFLOPs
  131 route  130 128
  132 conv    128  1 x 1 / 1    40 x  40 x 256   ->    40 x  40 x 128  0.105 BFLOPs
  133 conv    256  3 x 3 / 1    40 x  40 x 128   ->    40 x  40 x 256  0.944 BFLOPs
  134 conv    128  1 x 1 / 1    40 x  40 x 256   ->    40 x  40 x 128  0.105 BFLOPs
  135 conv    256  3 x 3 / 1    40 x  40 x 128   ->    40 x  40 x 256  0.944 BFLOPs
  136 conv    128  1 x 1 / 1    40 x  40 x 256   ->    40 x  40 x 128  0.105 BFLOPs
  137 conv    256  3 x 3 / 1    40 x  40 x 128   ->    40 x  40 x 256  0.944 BFLOPs
  138 conv     24  1 x 1 / 1    40 x  40 x 256   ->    40 x  40 x  24  0.020 BFLOPs
  139 yolo
Unused field: 'scale_x_y = 1.2'
Unused field: 'iou_thresh = 0.213'
Unused field: 'cls_normalizer = 1.0'
Unused field: 'iou_normalizer = 0.07'
Unused field: 'iou_loss = ciou'
Unused field: 'nms_kind = greedynms'
Unused field: 'beta_nms = 0.6'
Unused field: 'max_delta = 5'
  140 route  136
  141 conv    256  3 x 3 / 2    40 x  40 x 128   ->    20 x  20 x 256  0.236 BFLOPs
  142 route  141 126
  143 conv    256  1 x 1 / 1    20 x  20 x 512   ->    20 x  20 x 256  0.105 BFLOPs
  144 conv    512  3 x 3 / 1    20 x  20 x 256   ->    20 x  20 x 512  0.944 BFLOPs
  145 conv    256  1 x 1 / 1    20 x  20 x 512   ->    20 x  20 x 256  0.105 BFLOPs
  146 conv    512  3 x 3 / 1    20 x  20 x 256   ->    20 x  20 x 512  0.944 BFLOPs
  147 conv    256  1 x 1 / 1    20 x  20 x 512   ->    20 x  20 x 256  0.105 BFLOPs
  148 conv    512  3 x 3 / 1    20 x  20 x 256   ->    20 x  20 x 512  0.944 BFLOPs
  149 conv     24  1 x 1 / 1    20 x  20 x 512   ->    20 x  20 x  24  0.010 BFLOPs
  150 yolo
Unused field: 'scale_x_y = 1.1'
Unused field: 'iou_thresh = 0.213'
Unused field: 'cls_normalizer = 1.0'
Unused field: 'iou_normalizer = 0.07'
Unused field: 'iou_loss = ciou'
Unused field: 'nms_kind = greedynms'
Unused field: 'beta_nms = 0.6'
Unused field: 'max_delta = 5'
  151 route  147
  152 conv    512  3 x 3 / 2    20 x  20 x 256   ->    10 x  10 x 512  0.236 BFLOPs
  153 route  152 116
  154 conv    512  1 x 1 / 1    10 x  10 x1024   ->    10 x  10 x 512  0.105 BFLOPs
  155 conv   1024  3 x 3 / 1    10 x  10 x 512   ->    10 x  10 x1024  0.944 BFLOPs
  156 conv    512  1 x 1 / 1    10 x  10 x1024   ->    10 x  10 x 512  0.105 BFLOPs
  157 conv   1024  3 x 3 / 1    10 x  10 x 512   ->    10 x  10 x1024  0.944 BFLOPs
  158 conv    512  1 x 1 / 1    10 x  10 x1024   ->    10 x  10 x 512  0.105 BFLOPs
  159 conv   1024  3 x 3 / 1    10 x  10 x 512   ->    10 x  10 x1024  0.944 BFLOPs
  160 conv     24  1 x 1 / 1    10 x  10 x1024   ->    10 x  10 x  24  0.005 BFLOPs
  161 yolo
Unused field: 'scale_x_y = 1.05'
Unused field: 'iou_thresh = 0.213'
Unused field: 'cls_normalizer = 1.0'
Unused field: 'iou_normalizer = 0.07'
Unused field: 'iou_loss = ciou'
Unused field: 'nms_kind = greedynms'
Unused field: 'beta_nms = 0.6'
Unused field: 'max_delta = 5 '
Loading weights from yolov4.conv.137...Done!
Learning Rate: 0.001, Momentum: 0.949, Decay: 0.0005
Resizing
448
Loaded: 0.000064 seconds
**Segmentation fault (core dumped)**
```

**Comment by Renesis88** [comment]
Hi Alex. I have the same issue but running on my home PC.

./darknet detect cfg/yolov4.cfg yolov4.weights data/person.jpg
 CUDA-version: 10010 (10020), cuDNN: 8.0.2, CUDNN_HALF=1, GPU count: 1  
 CUDNN_HALF=1 
 OpenCV version: 4.2.0
 0 : compute_capability = 750, cudnn_half = 1, GPU: GeForce GTX 1660 Ti 
net.optimized_memory = 0 
mini_batch = 1, batch = 8, time_steps = 1, train = 0 
   layer   filters  size/strd(dil)      input                output
   0 
 cuDNN status Error in: file: /home/darknet/src/dark_cuda.c : () : line: 171 : build time: Aug 20 2020 - 21:36:58 

 cuDNN Error: CUDNN_STATUS_BAD_PARAM
cuDNN Error: CUDNN_STATUS_BAD_PARAM: Success

I tried your suggestion as above using the make command but the same error happens. Any suggestions ?
