### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by MaeThird** [pjreddie/darknet#239]
latest darknet was compiled with GPU=1 CUDNN=1 OPENCV=1 OPENMP=1 DEBUG=1 on my PC.
When I start to train like `./darknet detector train cfg/face.data cfg/yolo-face.2.0.cfg tmp_mk_data/backup/yolo-face_900.weights -gpus 0`the MEM is about `14% `,after hundred batches the MEM finally reached `99%` and darknet was killed by kernel.There are 24Gib cpu memory and 4Gib GPU memory on my PC.
I used the mtrace tool to find the leak.It turned out leaks in `list.c:42 0x18 bytes ,utils.c:292 0x200 bytes` and others leaks in using libcudnn.so.
In the next days I'll try it more.

**Comment by ouceduxzk** [comment]
@MaeThird  I run darknet on ubuntu 16 with webcam, it seems the memory usage is keep increasing slowly, any update?

**Comment by ToExperienceMore** [comment]
yes

**Comment by ToExperienceMore** [comment]
There is GPU memory leak too.I have fixed it as much as I can. At the end, the memory of cpu and  GPU will grow as I init and deinit for more times, but will not grow when I just process more pics.And when I use the cpu mode,the cpu mem leak dispear. Look forward to your update,tks

**Comment by fqd2009** [comment]
@ToExperienceMore Could you show your code and teach me know how to solve this memory leak problem ?  It brothers me every day~thanks very much~
