### ISSUE TITLE
"Cuda malloc failed : No error" in tiny-yolo-voc training

### ISSUE THREAD

**Issue by primat000** [pjreddie/darknet#473]
I tried to train  yolo-voc, but out of memory. Now i want try to train tiny-yolo, but "Cuda malloc failed". I would be grateful if you tell me is it the same problem(i haven't enough memory) or the reason is different?
C:\Users\key\Desktop\YOLO\darknet\build\darknet\x64>darknet.exe detector train data/voc.data yolo-voc.2.0.cfg darknet19_448.conv.23
yolo-voc
layer     filters    size              input                output
    0 conv     32  3 x 3 / 1   416 x 416 x   3   ->   416 x 416 x  32
    1 max          2 x 2 / 2   416 x 416 x  32   ->   208 x 208 x  32
    2 conv     64  3 x 3 / 1   208 x 208 x  32   ->   208 x 208 x  64
    3 max          2 x 2 / 2   208 x 208 x  64   ->   104 x 104 x  64
    4 conv    128  3 x 3 / 1   104 x 104 x  64   ->   104 x 104 x 128
    5 conv     64  1 x 1 / 1   104 x 104 x 128   ->   104 x 104 x  64
    6 conv    128  3 x 3 / 1   104 x 104 x  64   ->   104 x 104 x 128
    7 max          2 x 2 / 2   104 x 104 x 128   ->    52 x  52 x 128
    8 CUDA Error: out of memory
CUDA Error: out of memory: No error

C:\Users\key\Desktop\YOLO\darknet\build\darknet\x64>darknet.exe detector train data/voc.data tiny-yolo-voc.cfg darknet19_448.conv.23
tiny-yolo-voc
layer     filters    size              input                output
    0 conv     16  3 x 3 / 1   416 x 416 x   3   ->   416 x 416 x  16
    1 max          2 x 2 / 2   416 x 416 x  16   ->   208 x 208 x  16
    2 conv     32  3 x 3 / 1   208 x 208 x  16   ->   208 x 208 x  32
    3 max          2 x 2 / 2   208 x 208 x  32   ->   104 x 104 x  32
    4 conv     64  3 x 3 / 1   104 x 104 x  32   ->   104 x 104 x  64
    5 max          2 x 2 / 2   104 x 104 x  64   ->    52 x  52 x  64
    6 conv    128  3 x 3 / 1    52 x  52 x  64   ->    52 x  52 x 128
    7 max          2 x 2 / 2    52 x  52 x 128   ->    26 x  26 x 128
    8 conv    256  3 x 3 / 1    26 x  26 x 128   ->    26 x  26 x 256
    9 max          2 x 2 / 2    26 x  26 x 256   ->    13 x  13 x 256
   10 conv    512  3 x 3 / 1    13 x  13 x 256   ->    13 x  13 x 512
   11 max          2 x 2 / 1    13 x  13 x 512   ->    13 x  13 x 512
   12 conv   1024  3 x 3 / 1    13 x  13 x 512   ->    13 x  13 x1024
   13 conv   1024  3 x 3 / 1    13 x  13 x1024   ->    13 x  13 x1024
   14 conv    125  1 x 1 / 1    13 x  13 x1024   ->    13 x  13 x 125
   15 detection
Loading weights from darknet19_448.conv.23...
 seen 32
Done!
Learning Rate: 0.001, Momentum: 0.9, Decay: 0.0005
Resizing
352
Cuda malloc failed
: No error

**Comment by sivagnanamn** [comment]
Looks like your GPU doesn't have enough memory to load the batch of images.

Could to try to reduce the `batch` (or) increase the `subdivisions`?

Monitor your GPU memory consumption during training and use the best `batch` & `subdivisions` combination to utilize your GPU fully.

**Comment by primat000** [comment]
Thanks a lot for your advise. I have looked nvidia control panel with system information, it says I have 2GB didecated memory, but when I was monitoring my windows performance monitor GPU dedicated memory was always fully with defferent combination batch & subdivisions. Probably I really haven't enough memory.

**Comment by sivagnanamn** [comment]
You can try setting `random=0` , `batch=64`, `subdivisions=32` to check. This will divide one training iteration(with batch=64 images) into 32 sub-iterations( since subdivisions=32, 64/32 = 2 images per sub-iteration). This setting shouldn't need more memory for training. You can keep reducing the subdivision size to fit your GPU memory size.

**Comment by primat000** [comment]
Thanks a lot now it's working!

**Comment by saiteja-ada** [comment]
> You can try setting `random=0` , `batch=64`, `subdivisions=32` to check. This will divide one training iteration(with batch=64 images) into 32 sub-iterations( since subdivisions=32, 64/32 = 2 images per sub-iteration). This setting shouldn't need more memory for training. You can keep reducing the subdivision size to fit your GPU memory size.

Thanks a lot. Its working now.
