### ISSUE TITLE
CUDA Error: unknown error 

### ISSUE THREAD

**Issue by sezan92** [pjreddie/darknet#748]
Hello. My system is
Ubuntu 14.04 65 bit architecture 
GPU NVIDA geforce 920mx 
Cuda 8.0 , cudnn 5.1

But everytime i run ```./darknet imtest data/eagle.jpg``` after Gpu installation, this error comes
```CUDA Error: unknown error
darknet: ./src/cuda.c:36: check_error: Assertion `0' failed.
Aborted (core dumped)
```

**Comment by xhzzhang** [comment]
I have same issue, dont know how to fix it.

**Comment by xhzzhang** [comment]
My message is : CUDA Error: an illegal memory access was encountered
darknet: ./src/cuda.c:36: check_error: Assertion `0' failed.
CUDA Error: an illegal memory access was encountered

**Comment by ahsan856jalal** [comment]
try
./darknet detector test data/coco.data cfg/yolo.cfg yolo.weights
data/eagle.jpg
Note: data,cfg and weight files can have different names and directories
based on you
Regards
Ahsan

**Comment by ahsan856jalal** [comment]
you can also specify GPU
./darknet detector test data/coco.data cfg/yolo.cfg yolo.weights
data/eagle.jpg -i 0[1 or 2]

Regards
Ahsan

**Comment by ciwei123** [comment]
@sezan92 ,Hi, have you fix that error?  I have same issue, dont know how to fix it. Thanks~

**Comment by ciwei123** [comment]
> @ciwei123 no i couldnt , i had to run on another machine

Is the computer configuration causing an error?Could you tell me that machine's configuration?Thank you very much!

**Comment by darthdeus** [comment]
Same problem for me

```
layer     filters    size              input                output
    0 CUDA Error: unknown error
darknet: ./src/cuda.c:36: check_error: Assertion `0' failed.
[1]    23456 abort (core dumped)  ./darknet detect cfg/yolov3.cfg yolov3.weights data/dog.jpg
```

**Comment by AKSHANSH47** [comment]
12 darknet: ./src/cuda.c:36: check_error: Assertion `0' failed.
yolov3
CUDA Error: out of memory
I am facing the same problem

**Comment by darthdeus** [comment]
@AKSHANSH47 It doesn't look like the same error. Yours says _out of memory_ and not _unknown error_. You're probably just running out of GPU RAM.

**Comment by MedAliMimouni** [comment]
Guy for me I restarted my computer and it worked fine.
if the error still, you can rebuild the darknet on your computer.
